### ISSUE TITLE
Fedora packages

### ISSUE THREAD

**Issue by rapgro** [mhogomchungu/ecryptfs-simple#2]
Hi,
there are now official packages ¹ available in Fedora repositories. I fail to build a package for epel7 because we don't have ecryptfs-utils there and the kernel of RHEL7 ² does not have support for ecryptfs.
Further, I added ecryptfs-simple as a weak (=optional) dependency to my zulucrypt packages in Fedora.
¹ https://bodhi.fedoraproject.org/updates/?packages=ecryptfs-simple
² https://bugzilla.redhat.com/show_bug.cgi?id=1178673#c4

**Comment by mhogomchungu** [comment]
Reading this post[1] suggests the binary does not have suid bit set. Is this so? if yes,then zuluMount-gui will have to be modified to accommodate this ecryptfs-simple configuration.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1402590#c8

**Comment by rapgro** [comment]
Well, there's a rpmlint policy ¹ in Fedora to prevent setuid flags as good as possible. zuluMount-gui gets executed via pkexec to have root rights, so the forked ecryptfs-simple process should indirectly inherit that as well. What configuration do you want to get changed?
¹ https://taskotron.fedoraproject.org/artifacts/all/bc201cae-fdfe-11e6-bff0-5254008e42f6/task_output/ecryptfs-simple-2016.11.16.1-2.fc24.log

**Comment by mhogomchungu** [comment]
ecryptfs-simple can run in two configurations.

The default configuration is the one where suid bit is set allowing it to work from normal user account.

The other configuration is the one you are going with.This configuration removes the suid bit forcing all users of the application to run it from root's account.

The technical term i use to describable the way zuluCrypt GUI components runs in fedora and debian is "mixed mode". This mode runs GUI from root's account but they serve a normal user.

Currently, zuluMount-gui supports only the first configuration and it will have to be modified to support the second configuration.

FUSE based mount points by default allows only the person who created the mount point to access them and when zuluMount-gui is running in mixed more,it drops its root's privileges and takes the personality of the normal user before calling these file based encrypted volumes.

ecryptfs is not FUSE based but ecryptfs-simple took the same code paths FUSE based backends where using because its unique behaviors made no difference as far as code paths were concerned.

The above means,currently,ecryptfs-simple will run with normal user privileges even though zuluMount-gui was started with pkexec. The change zuluMount-gui will have to make is to not drop privileges when its about to call ecryptfs-simple when its running in mixed more.

**Comment by mhogomchungu** [comment]
ecryptfs-simple does not seem to work as expected on my system when it does not have suid bit set.

If you have sirikali[1] installed:

1. Log in to root's account through ```su -``` and then create an ecryptfs volume and it will work.

2. Log in to root's account through ```su``` and then create an ecryptfs volume and it will not work.

3. Log in to root's account through pkexec and then create an ecryptfs volume and it will not work(tested this one through zuluMount-gui started with pkexec.

When things fail,generated errors looks like below here:

```
Mar  3 13:32:50 ink klogd: Could not find key with description: [1b77138d91206e66]
Mar  3 13:32:50 ink klogd: process_request_key_err: No key
Mar  3 13:32:50 ink klogd: Could not find valid key in user session keyring for sig specified in mount option: [1b77138d91206e66]
Mar  3 13:32:50 ink klogd: One or more global auth toks could not properly register; rc = [-2]
Mar  3 13:32:50 ink klogd: Error parsing options; rc = [-2]
[mtz@ink ~]$ 

```

ecryptfs uses kernel keyring[2] and why does things work with ```su -``` and not with anything else remains a mystery to me and my guess is that the keyring works only with a full logged in user and not with a pretending one as created with ```su```,```pkexec``` or. with ```sudo```.


[1] https://github.com/mhogomchungu/sirikali

[2] http://man7.org/linux/man-pages/man7/keyrings.7.html

**Comment by mhogomchungu** [comment]
The git version should now work with ecryptfs-simple that does not have suid bit set and with zuluMount-gui running in mixed mode.

If you are curious,the trick i did was to not drop privileges[1] when unlocking ecryptfs volume and to call ecryptfs-simple using "su -"[2]. Calling su will not require root's password because we are already root.The string generated at line 263 will look like below

```
/bin/su - -c "/usr/bin/ecryptfs-simple -o key=passphrase --readonly -a --config "/home/mtz/ecryptfs/.ecryptfs.config" "/home/mtz/ecryptfs" "/run/media/private/mtz/ecryptfs""
```

[1] https://github.com/mhogomchungu/zuluCrypt/blob/061c57891f180c13d728a851336cca03a203f116/zuluMount-gui/siritask.cpp#L64

[2] https://github.com/mhogomchungu/zuluCrypt/blob/061c57891f180c13d728a851336cca03a203f116/zuluMount-gui/siritask.cpp#L255

Thanks for the info about ecryptfs-simple making it to fedora.

**Comment by mhogomchungu** [comment]
Tested the above on fedora 25 and can self confirm that ecryptfs-simple without suid bit does not work with the version of zuluCrypt in fedora but it works with the git version.

I also noticed a UI bug in the polkit prompt for the project as seen below. I think the text should read

``` 
Authentication is required to run zuluCrypt
```

The bug is also there in zuluMount prompt.

![screenshot_20170304_075231](https://cloud.githubusercontent.com/assets/3496115/23576521/e0875578-00b8-11e7-97be-743365cdfcfe.png)

**Comment by rapgro** [comment]
Thanks for testing and the hotfix. It's quite curious about su and su -l in Fedora. I remember there was a bug with systemd without proper initialization of the environment.
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1429090

**Comment by mhogomchungu** [comment]
I have reported the odd behavior in encrypts bug tracker at: https://bugs.launchpad.net/ecryptfs/+bug/1669982

This[1] bug seems to be related to ours.

[1] https://bugs.launchpad.net/ecryptfs/+bug/1615412

**Comment by mhogomchungu** [comment]
How do you plan to support ecryptfs-simple with SiriKali when ecryptfs-simple does not have suid bit set?

ecryptfs-simple backend will require elevated privileges but the rest of the supported backends do not.

One solution is to do things the way zuluMount-gui does it,elevate the frontend with pkexec at startup and then internally dropping the privileges before contacting FUSE based backends. The polkit prompt will be an unnecessary inconvenience to all users of FUSE based backends.

Another solution is to start SiriKali normally from a normal user account and then call pkexec only when managing ecryptfs volumes. This will work best for FUSE based users but will be annoying for ecryptfs users since they will get a prompt everytime they create,unlock or lock a volume.

Another solution is to leave SiriKali as is and tell people to start it from root's account if they want to create ecryptfs volume and to use zuluMount-gui to unlock their ecryptfs volumes. In other words,SiriKali from a normal user account is marked as being unusable to manage ecryptfs volumes.

Last solution is to split the application into two packages,one handles only ecryptfs volumes and get a pokit prompt at startup and another package handles only FUSE based backends and works without polkit.

I generally do not like pkexec solutions since they make an application unusable to non admin users and i would prefer the last option.

**Comment by mhogomchungu** [comment]
The git version can be build with an additional option of ```-DUSE_POLKIT=true```. This option will make SiriKali behaving like the first option mentioned above.
