### ISSUE TITLE
Debian Respository

### ISSUE THREAD

**Issue by teotikalki** [mhogomchungu/ecryptfs-simple#4]
I attempted to install by following the instructions here: https://software.opensuse.org/download.html?project=home%3Amhogomchungu&package=ecryptfs-simple

I installed the key correctly, and 'apt update ' gives me this: 

W: GPG error: http://download.opensuse.org/repositories/home:/mhogomchungu/Debian_8.0  Release: The following signatures were invalid: 1684885B6FFA57BD2576354F007312F085D89AA2
E: The repository 'http://download.opensuse.org/repositories/home:/mhogomchungu/Debian_8.0  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

I tried the following to resolve this:
1.) apt-key adv --keyserver keyserver.opensuse.org --recv-keys 1684885B6FFA57BD2576354F007312F085D89AA2
2.) gpg --keyserver keyserver.opensuse.org --recv-keys 1684885B6FFA57BD2576354F007312F085D89AA2
3. changing the source to Ubuntu 17.04 and importing that key.

I can simply download and install the .deb to light up that menu item in SiriKali but that feels like failure... I want to be able to write a blog entry describing the proper complete setup in Debian Stretch (I spend a lot of time researching/testing open source software and).

**Comment by teotikalki** [comment]
I wanted to add that I am unsure about the appropriateness of posting this HERE, but I couldn't locate a bug report submission at software.opensuse .org and this was the best place I could think of. I stand ready to be educated if there is a better way. :)

**Comment by mhogomchungu** [comment]
I know about this problem and the bug report that tracks it is this[1] one. A lot of bug reports that reported the issue appear to be closed but i dont see a solution i can act on in any of them and i am just hoping the problem will eventually sort it self out because i have no idea how to solve it on my end if its possible

Did importing the key from .Ubuntu 17.04 removed the problem? If yes then i think the problem will also be fixed when debian stretch is released and they start supporting it.

[1] https://github.com/openSUSE/obs-sign/issues/5

**Comment by teotikalki** [comment]
It did not.

**Comment by mhogomchungu** [comment]
I have added an entry in that bug report and hopefully something will come of it.

**Comment by teotikalki** [comment]
Thank you. Is there any further action that I can take? I want to contribute as much as I can.

**Comment by mhogomchungu** [comment]
How did you come to know about SiriKali?

I do not think there is anything you can do as far as open suse build service is concerned.

The most important thing is FOSS is user feedback and i think the best thing you can do for SiriKali and ecryptfs-simple among my other projects is to report issues you observe or anything you think will make  projects better when changed.

**Comment by teotikalki** [comment]
I think that I originally found it when doing a search for 'crypto' in Synaptic on Debian Jessie. It was reading your website that led me to know of the Zulu programs which I have just installed and will play with soon. I've been reading some material about the different purposes they serve. Thanks again for your work, btw. :)

**Comment by mhogomchungu** [comment]
debian zuluCrypt packages as provided by debian do not offer the user experience i want and i would advice to use debian packages i provide in zuluCrypt's home page.

**Comment by teotikalki** [comment]
I just checked and the website (https://mhogomchungu.github.io/zuluCrypt/) has version 5.1.0 whereas the Debian Testing repository has 5.0.2-2 . May I ask what the difference is? (I prefer to have apt handling my installed software, tbh, if at all possible.) If your repository worked properly I should be able to upgrade to a newer version there I'm guessing, although you don't have a .deb for Debian Stretch.
It is my understanding that Debian Testing software is only delayed by a few weeks from the upstream updates and that it tracks those updates as long as there is no bug discovered in the intervening time? Will the Testing repository thus have an up-to-date version by May?

**Comment by mhogomchungu** [comment]
My suspicion is that the debian maintainer prefers to be one version behind for reason i do not know because i have not asked him but i noticed this pattern a long time ago.

The different between packages i provide and packages debian provides is how GUI elements are started. In packages i provide,start GUI application and they just start from your normal user account and they look and feel like any other application in your normal user account. In other words,nothing different appear to be happening.

In debian packages,start the GUI and you will get a polkit prompt where you have to enter the root's password and then the GUI will run from root's account and they will look and feel foreign.. If you can live with the polkit prompt and foreign looking GUI then its fine to use it. If you go this route then please report if you experience a GUI hanging when working on a volume since this setup had a problem i released version 5.0.2 to solve it.

The next version of zuluCrypt(5.2.0) will keep the polkit prompt but it will have GUI elements running in the normal user session making them look and feel like any other Qt GUI application running in the user session.



[1] https://github.com/mhogomchungu/zuluCrypt/blob/26c772424fc89328d37e75cbf967f16dedfc3892/changelog#L259

**Comment by mhogomchungu** [comment]
It should now be possible to install ecryptfs-simple[1]/SiriKali[2] through synaptic/apt-get without any errors by following instructions from here[1].

The solution i went with is to create a new account since new accounts are created with appropriate keys. I do not know why they do not want to upgrade users with old accounts that want to upgrade.

Will appreciate if you could confirm that it works since i dont have a debian/ubuntu system and can not test for myself.

[1] http://software.opensuse.org//download.html?project=home%3Aobs_mhogomchungu&package=ecryptfs-simple

[2] http://software.opensuse.org//download.html?project=home%3Aobs_mhogomchungu&package=sirikali

**Comment by hameau** [comment]
Hello,

The reported problem still exists with Debian 9 (stretch), using the repository link in ```README.md```.

@mhogomchungu : Have you seen https://github.com/openSUSE/obs-sign/issues/5#issuecomment-331432648 ?

If I use your ```obs_mhogomchungu``` repository, the Release key is fine, but I am only offered i386 (my system is amd64, but is Multiarch enabled) packages in ```apt```.

I am using manually downloaded packages for the moment, but it would be nice to have a working repository.

**Comment by mhogomchungu** [comment]
I have updated the readme file to now point to "obs_mhogomchungu" repository and i will retire "mhogomchungu" repository sooner or later as it is no longer meant to be used to fetch packages.

Using synaptic,just searching for "ecryptfs-simple" gives only the i386 version but the amd64 version is there.

You can install it through synaptic using the 3 steps highlighted in the screenshot below. I do not know why amd64 version does not show by default.

![screenshot_20171018_164428](https://user-images.githubusercontent.com/3496115/31722365-8e5ac878-b424-11e7-9ea2-007b71f8462c.png)

**Comment by mhogomchungu** [comment]
I think this issue should be closed since moving to "obs_mhogomchungu" repository solved the reported problem.

**Comment by hameau** [comment]
Thanks for your response – all resolved now.
